server:
  port: 7879
spring:
  application:
    name: configClient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  rabbitmq:
    host: 192.168.144.77
    port: 5672
    username: test
    password: 123456
